version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=windi_chat
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: